source 'https://rubygems.org'
gem 'github-pages'
# gem 'github-linguist'
# gem 'rinku'
# gem 'escape_utils'
# gem 'email_reply_parser'
# gem 'gemoji'
# gem 'github-markdown'
# gem 'sanitize'
# gem 'RedCloth'